packages:
- skylighting-core
- skylighting
- skylighting-format-ansi
- skylighting-format-blaze-html
- skylighting-format-context
- skylighting-format-latex
extra-deps:
- xml-conduit-1.9.1.3
resolver: lts-18.10
ghc-options:
    "$locals": -Wall -optP-Wno-nonportable-include-path
